const Routes = {
  hero: '/',
  studentLogin: '/login/student',
  registerStudentPart1: '/register/student/part1',
  registerStudentPart2: '/register/student/part2',
  registerAdultPart1: '/register/adult/part1',
  registerAdultPart2: '/register/adult/part2',
  adultLogin: '/login/adult',
  studentDashboard: '/aliendashboard',
  dashboard: '/dashboard',
  challenge: '/challenge/play',
  teacherClasses: '/classrooms/teacher/',
  classDetails: '/classrooms/teacher/details/',
  leaderboard: '/classrooms/leaderboard/',
  accessByForgotPassword: '/forgotpassword/question',
  resetPasswordByEmail: '/forgotpassword/resetbyemail/',
  privacyPolicy: '/privacypolicy',
  termsOfService: '/termsofservice',
  accessByEmail: '/forgotpassword/email',
  createClass: '/classrooms/create',
  stats: '/stats/',
  account: '/account',
  logout: '/logout',
  fourOhFour: '*',
  unauthorized: '/unauthorized',
  deleted: '/deleted',
  mobile: '/mobile',
};

export default Routes;
